#!/bin/bash
# dbg - run gdb and attach it to sys161
#
# Copyright © 2013 Eon S. Jeon <esjeon@live.com>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#

### Constants
ROOT="$HOME/cs350-os161/root"
SRCTREE="$HOME/cs350-os161/os161-1.11/"
SCRIPT=".gdbscript"


### Parse arguments

ASST="x"

for i; do
	case "$i" in
	[0-5])
		ASST="$i" ;;
	esac
done

if [[ "${ASST}" = "x" ]]; then
	echo Assignment number is not specified
	exit 1
fi


### String Variables
KERN="kernel-ASST${ASST}"
SOCK=".sockets/gdb"
OBJDIR="${SRCTREE}/kern/compile/ASST${ASST}/"


### Run debugger
cd "${ROOT}"

cat << EOF > "${SCRIPT}"
dir ${OBJDIR}
target remote unix:${SOCK}
EOF

cs350-gdb -x "${SCRIPT}" "${KERN}"

rm "${SCRIPT}"
